---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - newproj.controller.proj
  resources:
  - svcmergerobjs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - newproj.controller.proj
  resources:
  - svcmergerobjs/finalizers
  verbs:
  - update
- apiGroups:
  - newproj.controller.proj
  resources:
  - svcmergerobjs/status
  verbs:
  - get
  - patch
  - update
