# permissions for end users to view svcmergerobjs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: svcmergerobj-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controllerproj
    app.kubernetes.io/part-of: controllerproj
    app.kubernetes.io/managed-by: kustomize
  name: svcmergerobj-viewer-role
rules:
- apiGroups:
  - newproj.controller.proj
  resources:
  - svcmergerobjs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - newproj.controller.proj
  resources:
  - svcmergerobjs/status
  verbs:
  - get
