apiVersion: v1
kind: Service
metadata:
  name: web-1-svc

spec:
  selector:
    app: web1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-2-svc

spec:
  selector:
    app: web2
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-3-svc

spec:
  selector:
    app: web3
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8080